import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/header/header";
import Footer from "./common/footer/footer";
import OpenDays from "./common/open-days/opendays";
import Countries from "./common/countries/countries";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <OpenDays />
          <section className="bg-neutral-50">
            <div className="max-w-container mx-auto">
              {children}
            </div>
          </section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
