import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/headercomponents";
import Footer from "./components/footer/footercomponents";
import OpenDays from "./components/open-days/opendayscomponents";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <OpenDays />
          <section className="bg-neutral-50">{children}</section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
